/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_SHA512 */

#ifndef _Included_my_SHA512
#define _Included_my_SHA512
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_SHA512
 * Method:    sha512
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_my_SHA512_sha512
(JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
